network.host: 0.0.0.0
node.name: ${HOSTNAME}
cluster.name: "elk-cluster"
path:
  logs: /var/log/elasticsearch
  data: /var/data/elasticsearch

# Disable xpack
xpack.graph.enabled: "false"
xpack.watcher.enabled: "false"
xpack.security.enabled: "false"
xpack.monitoring.enabled: "false"

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1
